In [1]:
import itertools
import numpy

In [2]:
def check(x,n):
    for i in range(n):
        for j in range(n):
            if x[i][j]!=n*n:
                if i==0:
                    k=[1]
                elif i==n-1:
                    k=[n-2]
                else:
                    k=[i-1,i+1]

                if j==0:
                    l=[1]
                elif j==n-1:
                    l=[n-2]
                else:
                    l=[j-1,j+1]
                

                
                for m in k:
                    for o in l:
                        if x[i][j]+1==x[i][o]:

                            break
                        if x[i][j]+1==x[m][j]:

                            break
                    else:
                        continue
                    break
                else:

                    break
        else:
            continue
        break
    else:
        return x
    return numpy.zeros((n,n))

In [3]:
a=list(itertools.permutations([1,2,3,4]))
a=numpy.array(a)

In [4]:
b=[]
for i in a:
    b.append(numpy.reshape(i,(2,2)))

In [5]:
c=[]
for i in b:
    if check(i,2)[0][0]!=0:
        c.append(check(i,2))

In [6]:
c

[array([[1, 2],
        [4, 3]]),
 array([[1, 4],
        [2, 3]]),
 array([[2, 1],
        [3, 4]]),
 array([[2, 3],
        [1, 4]]),
 array([[3, 2],
        [4, 1]]),
 array([[3, 4],
        [2, 1]]),
 array([[4, 1],
        [3, 2]]),
 array([[4, 3],
        [1, 2]])]

In [7]:
a=list(itertools.permutations([1,2,3,4,5,6,7,8,9]))
a=numpy.array(a)
b=[]
for i in a:
    b.append(numpy.reshape(i,(3,3)))

In [8]:
d=[]
for i in b:
    if check(i,3)[0][0]!=0:
        d.append(check(i,3))

In [10]:
len(d)

40