In [1]:
import numpy

In [2]:
from itertools import combinations

In [3]:
a=[]
for i in combinations([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],8):
    b=numpy.matrix([[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]])
    for j in range(4):
        for k in range(1,5):
            for l in i:
                if j*4+k==l:
                    b[j,k-1]=1
            if numpy.linalg.det(b)==0:
                a.append(b)

In [4]:
a[0:10]

[matrix([[1, 1, 1, 1],
         [1, 1, 1, 1],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]),
 matrix([[1, 1, 1, 1],
         [1, 1, 1, 1],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]),
 matrix([[1, 1, 1, 1],
         [1, 1, 1, 1],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]),
 matrix([[1, 1, 1, 1],
         [1, 1, 1, 1],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]),
 matrix([[1, 1, 1, 1],
         [1, 1, 1, 1],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]),
 matrix([[1, 1, 1, 1],
         [1, 1, 1, 1],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]),
 matrix([[1, 1, 1, 1],
         [1, 1, 1, 1],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]),
 matrix([[1, 1, 1, 1],
         [1, 1, 1, 1],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]),
 matrix([[1, 1, 1, 1],
         [1, 1, 1, 1],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]),
 matrix([[1, 1, 1, 1],
         [1, 1, 1, 1],
         [0, 0, 0, 0],
         [0, 0, 0, 0]])]

In [5]:
len(a)

189930

In [6]:
c=[]
for i in combinations([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],8):
    b=numpy.matrix([[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]])
    for j in range(4):
        for k in range(1,5):
            for l in i:
                if j*4+k==l:
                    b[j,k-1]=1
            if numpy.linalg.det(b)!=0:
                c.append(b)

In [7]:
len(c)

15990

In [8]:
d=[]
'''for i in combinations([1,2,3,4,5,6,7,8,9],4):
    b=numpy.matrix([[0,0,0],[0,0,0],[0,0,0]])
    for j in range(3):
        for k in range(1,4):
            for l in i:
                if j*3+k==l:
                    b[j,k-1]=1
            if numpy.linalg.det(b)!=0:
                d.append(b)'''
for i in combinations([1,2,3,4,5,6,7,8,9],5):
    b=numpy.matrix([[0,0,0],[0,0,0],[0,0,0]])
    for j in range(3):
        for k in range(1,4):
            for l in i:
                if j*3+k==l:
                    b[j,k-1]=1
            if numpy.linalg.det(b)!=0:
                d.append(b)

In [9]:
len(d)

152

In [10]:
def check30(a):
    b=0
    c=[]
    for i in range(3):
        for j in range(2):
            if i!=0 and (i+j+1)%3!=0:
                k=0
            if i!=1 and (i+j+1)%3!=1:
                k=1
            if i!=2 and (i+j+1)%3!=2:
                k=2
            if a[0,i]==1 and a[1,(i+j+1)%3]==1 and a[2,k]==1:
                return 0
            if a[0,i]==1 and a[1,(i+j+1)%3]==1 and a[2,k]==None:
                c.append((2,k))
            if a[0,i]==1 and a[1,(i+j+1)%3]==None and a[2,k]==1:
                c.append((1,(i+j+1)%3))
            if a[0,i]==None and a[1,(i+j+1)%3]==1 and a[2,k]==1:
                c.append((0,i))
            if a[0,i]!=None and a[1,(i+j+1)%3]!=None and a[2,k]!=None:
                b+=0
    if b==6:
        return 0
    if c==[]:
        for i in range(3):
            for j in range(3):
                if a[i,j]==None:
                    c.append((i,j))
    return c

In [11]:
def check31(a):
    b=0
    c=[]
    for i in range(6):
        if i<3:
            if a[i,0]==0 and a[i,1]==0 and a[i,2]==0:
                return 0
            if a[i,0]==0 and a[i,1]==0 and a[i,2]==None:
                c.append((i,2))
            if a[i,0]==0 and a[i,1]==None and a[i,2]==0:
                c.append((i,1))
            if a[i,0]==None and a[i,1]==0 and a[i,2]==0:
                c.append((i,0))
            if a[i,0]!=None and a[i,1]!=None and a[i,2]!=None:
                b+=1
        else:
            if a[0,i-3]==0 and a[1,i-3]==0 and a[2,i-3]==0:
                return 0
            if a[0,i-3]==0 and a[1,i-3]==0 and a[2,i-3]==None:
                c.append((2,i-3))
            if a[0,i-3]==0 and a[1,i-3]==None and a[2,i-3]==0:
                c.append((1,i-3))
            if a[0,i-3]==None and a[1,i-3]==0 and a[2,i-3]==0:
                c.append((0,i-3))
            if a[0,i-3]!=None and a[1,i-3]!=None and a[2,i-3]!=None:
                b+=1
    if b==6:
        return 0
    if c==[]:
        for i in range(3):
            for j in range(3):
                if a[i,j]==None:
                    c.append((i,j))
    return c

In [12]:
check31(numpy.matrix([[None,0,None],[0,None,None],[None,None,None]]))

[(0, 0), (0, 2), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]

In [13]:
numpy.shape(numpy.matrix([[1,None],[None,0]]))

(2, 2)

In [14]:
d=numpy.matrix([[None,None,None],[None,None,None],[None,None,None]])

In [15]:
e=[]

In [16]:
def cons(a,b):
    if b==0:
        f=check30(a)
        if f==0:
            e.append(a)
        else:
            for i in f:
                c=a.copy()
                c[i]=0
                cons(c,(b+1)%2)
    if b==1:
        f=check31(a)
        if f==0:
            e.append(a)
        else:
            for i in f:
                c=a.copy()
                c[i]=1
                cons(c,(b+1)%2)

In [17]:
cons(d,0)

In [18]:
len(e)

17568

In [19]:
g=[d]
for i in numpy.array(e):
    for j in g:
        if (i==j).all():
            break
    else:
        g.append(i)


In [20]:
len(g)

442

In [21]:
h=[]
for i in range(len(g)):
    for j in range(i+1,len(g)):
        if (g[i].T==g[j]).all():
            h.append(i)

In [22]:
for i in sorted(h,reverse=True):
    del g[i]

In [23]:
len(g)

223

In [24]:
g

[matrix([[None, None, None],
         [None, None, None],
         [None, None, None]], dtype=object),
 array([[0, 1, 0],
        [1, 0, 1],
        [0, 1, 0]], dtype=object),
 array([[0, 1, 0],
        [1, 1, 1],
        [0, 0, 0]], dtype=object),
 array([[0, 1, 1],
        [1, 0, 0],
        [1, 0, 0]], dtype=object),
 array([[0, 1, 1],
        [1, 0, 1],
        [0, 0, 0]], dtype=object),
 array([[0, 1, 1],
        [1, 1, 0],
        [0, 0, 0]], dtype=object),
 array([[0, 0, 1],
        [1, 1, 0],
        [0, 0, 1]], dtype=object),
 array([[0, 0, 1],
        [0, 0, 1],
        [1, 1, 0]], dtype=object),
 array([[0, 0, 1],
        [1, 0, 1],
        [0, 0, 1]], dtype=object),
 array([[0, 0, 1],
        [1, 1, 1],
        [0, 0, 0]], dtype=object),
 array([[0, 0, 1],
        [1, 0, 1],
        [1, 0, 0]], dtype=object),
 array([[0, 0, 1],
        [0, 0, 0],
        [1, 1, 1]], dtype=object),
 array([[0, 0, 1],
        [1, 0, 0],
        [1, 0, 1]], dtype=object),
 array([[0, 0, 1],
  